[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "8Qx5W5JZB6EwPNdKHXKKqkKVwj42Bg5Fy6gARYsyy7St"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/who/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
